package com.mixam.mxjdf4.sdk;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SubProductType {
    INVALID(0),
    PRODUCT_HARD_COVER_BOOKS(1),
    PRODUCT_PAPERBACK_BOOKS(2),
    PRODUCT_PERFECT_BOOKLETS(3),
    PRODUCT_WIRO_BOOKLETS(4),
    PRODUCT_LOOP_BOOKLETS(5),
    PRODUCT_STAPLED_BOOKLETS(6),
    PRODUCT_MAGAZINES(7),
    PRODUCT_CATALOGS(8),
    PRODUCT_BOOKLETS(9),
    PRODUCT_ZINES(10),
    PRODUCT_COMIC_BOOKS(11),
    PRODUCT_ART_PRINTS(12),
    PRODUCT_MANGA(13),
    PRODUCT_WEDDING_BOOK(14),
    PRODUCT_YEARBOOK(15),
    PRODUCT_COOKBOOK(16),
    PRODUCT_COLOURINGBOOK(17),
    PRODUCT_ARTBOOK(18),
    PRODUCT_GRAPHIC_NOVEL(19),
    PRODUCT_LOOKBOOK(20),
    PRODUCT_MENUS(23),
    PRODUCT_CLASSIC_BOOKS(24),
    PRODUCT_DIARIES(21),
    PRODUCT_JOURNALS(22),
    PRODUCT_STICKER_RECTANGLE(61),
    PRODUCT_STICKER_CIRCLE(62),
    PRODUCT_STICKER_OVAL(63),
    PRODUCT_STICKER_ROUNDED_RECTANGLE(64),
    PRODUCT_CLASSIC_PAPERBACK_BOOKS(25),
    PRODUCT_FAMILY_HISTORY_BOOKS(26),
    PRODUCT_ACTIVITY_BOOKS(27),
    PRODUCT_MEMOIRS(28),
    PRODUCT_CHILDRENS_BOOKS(29),
    PRODUCT_WORKBOOKS(30),
    PRODUCT_PHOTO_BOOKS(31),
    PRODUCT_PHOTOGRAPHY_BOOKS(32),
    PRODUCT_COFFEE_TABLE_BOOKS(33),
    PRODUCT_MANUALS(34),
    PRODUCT_BABY_BOOKS(35),
    PRODUCT_BIOGRAPHY(36),
    PRODUCT_NOVELS(37),
    PRODUCT_POETRY_BOOKS(38),
    PRODUCT_SPIRAL_BOOKLETS(39),
    PRODUCT_GICLEE_ART_PRINTS_SMALL_FORMAT(40),
    PRODUCT_GICLEE_ART_PRINTS_LARGE_FORMAT(41),
    PRODUCT_STAPLED_CALENDAR(42),
    PRODUCT_NOTEBOOKS(43),
    PRODUCT_BOOKMARKS(44),
    PRODUCT_WIRO_CALENDAR(45),
    PRODUCTS_THESES(46),
    PRODUCT_DISSERTATIONS(47),
    PRODUCT_TEXTBOOKS(48),
    PRODUCT_HANDBOOKS(49),
    PRODUCT_POSTER_CALENDARS(50),
    PRODUCT_SKETCH_COVER_COMIC_BOOKS(51),
    PRODUCT_KITCHEN_CALENDARS(52),
    PRODUCT_SAMPLE_PACK_PRODUCTS(53),
    PRODUCT_SAMPLE_PACK_PAPER_SWATCHES(54),
    PRODUCT_SAMPLE_PACK_PROFESSIONAL(55),
    PRODUCT_SAMPLE_PACK_ULTIMATE(56),
    PRODUCT_CERTIFICATES(57),
    PRODUCT_INVITATIONS(58),
    PRODUCT_LOYALTY_CARDS(59),
    PRODUCT_REPORTS(60),
    PRODUCT_MIXAM_TEST(999999)
    ;

    private final int value;

    SubProductType(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }
}