name: Release MxJdf4

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Using qcastel/github-actions-maven-release because
      # by misusing docker-registry-* properties we can get
      # the two <server> entries we need into setting.xml
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          git-release-bot-name: github-actions
          git-release-bot-email: github-actions@github.com
          maven-repo-server-id: github
          maven-repo-server-username: github-actions@github.com
          maven-repo-server-password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
          docker-registry-id: github.com
          docker-registry-username: github-actions@github.com
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
